name = "BTA! packwiz example modpack"
author = "camoweed"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1a5a7ac7745436ef9945be028f34610f57d53387ed26703baa5ce8018bb68b3a"

[versions]
bta = "8.0"
fabric = "0.18.4-bta.11"
minecraft = "b1.7.3"
unsup = "1.2.7"

[options]
acceptable-game-versions = ["b1.7.3"]
